@host = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2MzQ2Nzg3MzB9.jezQcKluN1qMP2XHEHivK3ZauPUga-IG45Hn1fip0wE

# SESSIONS CREATE (login) #
  POST {{host}}/sessions.json
  Content-Type: application/json

  {
    "email": "test@gmail.com",
    "password": "password"
  }


# Users #
### USERS INDEX
  GET {{host}}/users.json
### USERS SHOW
  GET {{host}}/users/6.json
### USERS CREATE
  POST {{host}}/users.json
  Content-Type: application/json

  {
    "email": "test@gmail.com",
    "password": "password",
    "first_name": "sam",
    "zip_code": 401234,
    "profile_picture": "google.com/slaksjdlkj",
    "age": 24,
    "about_me": "looking to play magic for the first time!"
  }
### USERS UPDATE
  ATCH {{host}}/users/6
  Content-Type: application/json

  {
    "zip_code": 60067
  }
### USERS DESTROY
  DELETE {{host}}/users/6

# Messages #
### MESSAGES INDEX
  GET http://localhost:3000/messages.json
  Authorization: Bearer {{jwt}}

### MESSAGES SHOW
  GET {{host}}/messages/10.json
  Authorization: Bearer {{jwt}}

### MESSAGES CREATE
  POST {{host}}/messages.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
    "text": "blahblah",
    "receiver_id": 2
  }
### MESSAGES UPDATE
  PATCH {{host}}/messages/7
  Content-Type: application/json

  {
    "text": "blaksndlad"
  }
### MESSAGES DESTROY
  DELETE {{host}}/messages/6

# Relationships #
### Friendships
GET {{host}}/friends
Authorization: Bearer {{jwt}}

### RELATIONSHIP INDEX
  GET http://localhost:3000/relationships.json

### RELATIONSHIP SHOW
  GET {{host}}/relationships/6.json
### RELATIONSHIP CREATE
  POST {{host}}/relationships.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
    "responder_id": 4
  }
### RELATIONSHIP UPDATE
  PATCH {{host}}/relationships/7
  Content-Type: application/json

  {
    "status": "Accepted"
  }
### RELATIONSHIP DESTROY
  DELETE {{host}}/relationships/6

# next #