@host = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2MzUxMDgyNjR9.4hqebvgi9BEJZlmnfyR8oXtRXGyn0-wvz5sG4aWNJjA

# SESSIONS CREATE (login) #
  POST {{host}}/sessions.json
  Content-Type: application/json

  {
    "email": "test@gmail.com",
    "password": "password"
  }


# Users #
### USERS INDEX
  GET {{host}}/users.json
### USERS SHOW
  GET {{host}}/users/6.json
### USERS CREATE
  POST {{host}}/users.json
  Content-Type: application/json

  {
    "email": "test6@gmail.com",
    "password": "password",
    "first_name": "Sam",
    "zipcode": "60007",
    "profile_picture": "google.com/slaksjdlkj",
    "age": 24,
    "about_me": "looking to play magic for the first time!"
  }
### USERS UPDATE
  PATCH {{host}}/users/4.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}


  {
    "zipcode": 60018
  }
### USERS DESTROY
  DELETE {{host}}/users/6
  Authorization: Bearer {{jwt}}


# Messages #
### MESSAGES INDEX
  GET http://localhost:3000/messages.json
  Authorization: Bearer {{jwt}}

### MESSAGES SHOW
  GET {{host}}/messages/10.json
  Authorization: Bearer {{jwt}}

### MESSAGES CREATE
  POST {{host}}/messages.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
    "text": "Snake, this is a sneaking mission.",
    "receiver_id": 6
  }
### MESSAGES UPDATE
  PATCH {{host}}/messages/7
  Content-Type: application/json

  {
    "text": "blaksndlad"
  }
### MESSAGES DESTROY
  DELETE {{host}}/messages/6

# Relationships #
### Friendships
GET {{host}}/friends
Authorization: Bearer {{jwt}}

### RELATIONSHIP INDEX
  GET http://localhost:3000/relationships.json

### RELATIONSHIP SHOW
  GET {{host}}/relationships/6.json
### RELATIONSHIP CREATE
  POST {{host}}/relationships.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
    "responder_id": 4
  }
### RELATIONSHIP UPDATE
  PATCH {{host}}/relationships/7
  Content-Type: application/json

  {
    "status": "Accepted"
  }
### RELATIONSHIP DESTROY
  DELETE {{host}}/relationships/6

# next #
### ZIPCODE FIND
GET {{host}}/zipcodes/60443